version: 2.1

jobs:
  install-test-then-coverage:
    working_directory: /home/circleci/project
    resource_class: small
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - run:
          name: "Checkout submodules"
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run:
          name: "Install kcov"
          command: sudo apt-get install kcov
      - run:
          name: "Shellcheck"
          command: |
            . /home/circleci/project/task-runner.sh
            export TASK_MASTER_HOME=/home/circleci/project
            /home/circleci/project/test/shellcheck_all.sh
      - run:
          name: "Test"
          command: |
            . /home/circleci/project/task-runner.sh
            export TASK_MASTER_HOME=/home/circleci/project
            /home/circleci/project/test/test_all.sh
      - run:
          name: "Coverage"
          command: |
            . /home/circleci/project/task-runner.sh
            export TASK_MASTER_HOME=/home/circleci/project
            /home/circleci/project/test/coverage.sh
            bash <(curl -s https://codecov.io/bash) -s /home/circleci/project/test/kcov


workflows:
  default-workflow:
    jobs:
      - install-test-then-coverage
