version: 2.1

jobs:
  install-test-then-coverage:
    working_directory: /home/circleci/
    resource_class: small
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            ./bash-task-master/install-task-master.sh
      - run:
          name: "Test"
          command: |
            .task-master/test/test_all.sh
      - run:
          name: "Coverage"
          command: |
            .task-master/test/coverage.sh

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  default-workflow:
    jobs:
      - install-test-then-coverage
