version: 2.1

jobs:
  install-test-then-coverage:
    working_directory: /home/circleci/project
    resource_class: small
    docker:
      - image: cimg/base:2022.08
        environment:
          TASK_MASTER_HOME: /home/circleci/.task-master
    steps:
      - checkout
      - run:
          name: "Checkout submodules"
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run:
          name: "Install"
          command: |
            rm -r /home/circleci/.task-master
            /home/circleci/project/install-task-master.sh
      - run:
          name: "Test"
          command: |
            /home/circleci/.task-master/test/test_all.sh
      - run:
          name: "Coverage"
          command: |
            /home/circleci/.task-master/test/coverage.sh

workflows:
  default-workflow:
    jobs:
      - install-test-then-coverage
