readonly -f task_help
readonly -f task_list
readonly -f task_init
readonly -f task_edit
readonly -f task_goto
readonly -f task_record
readonly -f task_global
readonly -f task_export
readonly -f task_edit
readonly -f record_start
readonly -f record_stop
readonly -f record_trash
readonly -f record_restart
readonly -f record_extract_text_from_tasks
readonly -f persist_var
readonly -f remove_var
readonly -f export_var
readonly -f hold_var
readonly -f release_var
readonly -f clean_up_state
readonly -f set_return_directory
readonly -f load_state
readonly -f remove_file_value
readonly -f global_help
readonly -f global_debug
readonly -f global_set
readonly -f global_unset
readonly -f global_edit
readonly -f global_check-defs
readonly -f global_clean
readonly -f global_locations
readonly -f global_uuid
readonly -f arguments_global
readonly -f arguments_spawn
readonly -f arguments_record
readonly -f arguments_list
readonly -f arguments_init
readonly -f arguments_export
readonly -f validate_args_for_task
readonly -f parse_args_for_task

